services:
  shopware:
    build: ./
    container_name: kommandhub-paystack-shopware
    environment:
      - 'XDEBUG_ENABLED=0'
      - 'PHP_VERSION=8.3'
    volumes:
      # ----------------------------------------------------------------------------------------------------------------------------------
      # PLUGINS
      - "./:/var/www/html/custom/plugins/KommandhubPaystackSW"
      - "database:/var/lib/mysql"
      - "./Makefile:/var/www/html/Makefile"
      # - ".env.test:/var/www/html/.env.test"
      # ----------------------------------------------------------------------------------------------------------------------------------
      # EXCLUDE
      - "/var/www/html/custom/plugins/KommandhubPaystackSW/.git/"
      - "/var/www/html/custom/plugins/KommandhubPaystackSW/node_modules/"
      - "/var/www/html/custom/plugins/KommandhubPaystackSW/vendor/"
      # ----------------------------------------------------------------------------------------------------------------------------------

volumes:
  database:
    driver: local