name: PHP Composer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'
        extensions: mbstring, xml, ctype, iconv, intl, gd, zip, pdo_sqlite
        coverage: none

    - name: Validate composer.json and composer.lock
      run: composer validate --strict

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress

    - name: Run test suite
      run: |
        mkdir -p ../shopware/custom/plugins/KommandhubPaystackSW
        shopt -s dotglob
        cp -R * ../shopware/custom/plugins/KommandhubPaystackSW/
        cd ../shopware
        mkdir -p var
        ln -s custom/plugins/KommandhubPaystackSW/vendor vendor
        cd custom/plugins/KommandhubPaystackSW
        PROJECT_ROOT=$GITHUB_WORKSPACE/../shopware ./vendor/bin/phpunit --testdox
      env:
        DATABASE_URL: "sqlite3://localhost/var/test.sqlite"

    - name: Run static analysis
      run: ./vendor/bin/phpstan analyse src -c phpstan.dist.neon --no-progress

    - name: Run code style check
      run: ./vendor/bin/php-cs-fixer fix --dry-run --diff
